Setup automated docker build repository
Open-Network-Insight/spot-docker pull request #1
Opened 2017-01-07 00:22 UTC by natedogs911

This repo will be used for automated builds on the Docker hub and also for creation of new docker based images

2017-01-07 00:51 UTC, NathanSegerlind commented
how can I possibly review 1175 files?

2017-01-07 01:20 UTC, natedogs911 commented
To reduce the amount of files i can explore a few options:

1. host the `data` and `ipynb` folders in s3, develop a script to download them during the `docker build` stage
2. compress the files and unzip them by using `add` in the docker file

Everything outside of the before mentioned folders matches exactly https://github.com/apache/incubator-spot/tree/master/spot-oa

2017-01-09 16:09 UTC, EverLoSa commented
Is it required to have the OA (backend) module ? ,
 This demo is only for data visualization , right?

2017-01-09 17:34 UTC, natedogs911 commented
I can remove it in this implementation,

in future versions we need to automate the download of all dependencies then we're not uploading static code to this repository.

2017-01-18 17:14 UTC, EverLoSa requested changes

2017-01-18 17:14 UTC, EverLoSa commented on README.md
> +Each project sub folder is intended to be the source for the (Apache Spot organization)[https://hub.docker.com/u/apachespot/] on the (Docker Hub)[https://docs.docker.com/docker-hub/]
Markdown links are wrong formatted, links should be like:
 [Apache Spot](https://hub.docker.com/u/apachespot/)
[Docker Hub](https://docs.docker.com/docker-hub/)

2017-01-18 17:42 UTC, EverLoSa approved these changes

2017-01-18 17:42 UTC, EverLoSa commented
+1

2017-01-18 17:47 UTC, natedogs911 commented
@vgonzale78 can you merge?

2017-01-18 18:26 UTC, merged